classes:
  - PERSON_NAME
  - EMAIL
  - PHONE
  - ADDRESS
  - PIN_CODE
  - DATE_OF_BIRTH
  - AADHAAR
  - PAN
  - PASSPORT
  - VOTER_ID
  - DRIVING_LICENSE
  - BANK_ACCOUNT
  - IFSC
  - UPI_ID
  - CARD_NUMBER
  - PASSWORD
  - OTP
  - GSTIN
  - FACE
  - QR_BARCODE

label_to_id:
  O: 0
  B-PERSON_NAME: 1
  I-PERSON_NAME: 2
  B-EMAIL: 3
  I-EMAIL: 4
  B-PHONE: 5
  I-PHONE: 6
  B-AADHAAR: 7
  I-AADHAAR: 8
  B-PAN: 9
  I-PAN: 10
  B-BANK_ACCOUNT: 11
  I-BANK_ACCOUNT: 12
  B-OTP: 13
  I-OTP: 14
